apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-2bcdao
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2bcdao
  namespace: my-nginx-2bcdao
  labels:
    name: nginx-2bcdao
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-2bcdao
  template:
    metadata:
      namespace: my-nginx-2bcdao
      labels:
        name: nginx-2bcdao
    spec:
      containers:
      - name: nginx-2bcdao
        image: nginx
        ports:
        - containerPort: 80

