---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-228e3d638d46ed858caae044f39f0ba8
  name: wego-test-app-1ml0vn2y
  namespace: wego-system
spec:
  branch: main
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/my-test-org-23/wego-test-app-1ml0vn2y.git
